# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b44ef6cbbdcb236f8c3f259c375051c5665df2ffdb22ded0122471fa6438ac1128eb661d7e9e713b90d51437edd111de54178962ac488e8571787f53b09a0d1f

test:
  secret_key_base: 838341bc0333eafca480c1c3c7714621b8d7ffa34e899a63a6e68513a7ffe6550f188091ff0cfb74884d42677cee47ff7be174afaee183b8d69f8be1ad87adad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
